name: Build & Deploy swap‑rate page
on:
  push:
    branches: [ main ]
  schedule:
    # every 15 minutes (UTC)
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Show repo tree
      run: |
        echo "PWD=$(pwd)"
        echo "--- repo contents ----"
        ls -R
        echo "---------------------"

        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install deps
      run: pip install requests

    - name: Run rate script
      id: rates
      run: |
        python src/rate.py > data.json
        echo "DATA=$(cat data.json)" >> $GITHUB_ENV

    - name: Verify template path
      run: |
        echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
        echo "Listing $GITHUB_WORKSPACE/src"
        ls -al "$GITHUB_WORKSPACE/src" || true
        
    - name: Render HTML
      run: |
        python <<'PY'
        import json, os, html, pathlib

        # -------- paths --------
        root = pathlib.Path(os.environ["GITHUB_WORKSPACE"])   # repo root
        template_path = root / "src" / "template.html"
        dist_dir = root / "dist"
        dist_dir.mkdir(exist_ok=True)

        # -------- load data from the previous step --------
        with open(root / "data.json", encoding="utf‑8") as f:
            data = json.load(f)

        # -------- fill placeholders --------
        tpl = template_path.read_text(encoding="utf‑8")
        for k, v in data.items():
            tpl = tpl.replace(f"{{{{{k}}}}}", html.escape(str(v)))

        # -------- write final HTML --------
        (dist_dir / "index.html").write_text(tpl, encoding="utf‑8")
        PY


    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
